openapi: 3.0.3
info:
   title: Atom
   license:
      name: MIT
   version: 0.0.1
servers:
-  url: http://localhost:8080/atom/v1
paths:
   /schedule/meals:
      get:
         operationId: getScheduledMeals
         tags:
         - meal
         parameters:
         -  name: from
            in: query
            required: true
            schema:
               type: string
               format: date-time
         -  name: to
            in: query
            required: true
            schema:
               type: string
               format: date-time
         responses:
            '200':
               description: Expected response to a valid request
               content:
                 text/plain:
                   schema:
                      type: array
                      items:
                        $ref: "#/components/schemas/ScheduledMeal"
   /schedule/meal/{date}/{slot}:
      delete:
         operationId: deleteScheduledMeal
         tags:
         - meal
         parameters:
         -  name: date
            in: path
            required: true
            schema:
               type: string
               format: date
         -  name: slot
            in: path
            required: true
            schema:
               $ref "#/components/schemas/TimeSlot"
         responses:
            '200':
               description: Success
      put:
         operationId: putScheduledMeal
         tags:
         - meal
         parameters:
         -  name: date
            in: path
            required: true
            schema:
               type: string
               format: date
         -  name: slot
            in: path
            required: true
            schema:
               $ref "#/components/schemas/TimeSlot"
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ScheduledMeal"
         responses:
            '200':
               description: Success
components:
   schemas:
      ScheduledMeal:
         type: object
         properties:
            slot:
               $ref: "#/components/schemas/TimeSlot"
            date:
               type: string
               format: date
            recipe:
               $ref: "foods.yaml#/components/schemas/Recipe"
      TimeSlot:
         type: string
         enum:
         - MORNING
         - AFTERNOON
         - EVENING 
         - NIGHT